# Site settings
title: Gyuri Kim
description: Jekyll Theme Minimal Resume
baseurl: "https://gyuri.github.io" # the subpath of your site, e.g. /blog
url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Gyuri Kim
user_description: I'm an international student from University of Manitoba, always searching for the next challenge; no task is too scary nor too difficult. Lately I have been immersed in world of Giving Circles working with Grapevine, a California based startup trying to improve the world through collaborative giving. I'm the first engineer they hired to work on the platform.
user_title: Software Engineer
email: kimg2@myumanitoba.ca
# twitter_username: lorem_ipsum
#instagram_username: mauriciourraco7
#facebook_username: mauricio.urraco
#linkedin_username: murraco
github_username:  gyuyuu
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
